### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by vincentmaule** [OptimisticShaggy/LAB-101-html-boilerplate-linting-and-code-style#1]
## Upgrade the code from your last project to fully valid (and clean) HTML

@egillespie Can you take a look at this? It's [hosted here](https://OptimisticShaggy.github.io/LAB-101-html-boilerplate-linting-and-code-style/index.html) and meets the following criteria:

- [x] The files from your last project are copied and pasted into the directory for this project
- [x] Your code returns no errors (warnings are OK) when pasted into the [W3C Validator](https://validator.w3.org/#validate_by_input) (this will also be expected for all future projects)
- [x] Consistent spacing and indentation are used on every line (this will also be expected for all future projects)
- [x] `skeleton.css` is used to improve the design of the page

**Comment by egillespie** [comment]
Wow, you made quick work of this and the results are really nice! The HTML is well-formatted and I like how Skeleton styles look when applied to your page. Nicely done! 👏 :shipit:

**Comment by vincentmaule** [comment]
I learned to work the CSS Framework, Skeleton. Thought it was awesome and excited I learned a little more!
